name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run LeetCode Sync
        uses: faisal-shb/leetcode-sync@v1.1.0
        with:
          github_token: ${{ github.token }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          leetcode_csrf_token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          folder_format: 'title' 


